spring:
  datasource:
    username: report
    password: report
    url: jdbc:postgresql://localhost:5432/report?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    